version: '3'

networks:
  external:
  internal:

services:
  solr_test: 
    image: solr:6.3.0
    expose:
      - 8983
    networks:
      internal:
    volumes:
      - ./solr/config:/opt/solr/server/solr/configsets/data_driven_schema_configs
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - test
    environment: 
      - VERBOSE=yes
  db-test:
    image: mariadb:5.5
    expose:
      - 3306
    networks:
      internal:
    environment:
      - MYSQL_ROOT_PASSWORD=ABRACADABRA
      - MYSQL_PASSWORD=ABRACADABRA
      - MYSQL_DATABASE=spotlighttest
      - MYSQL_USER=roto
    volumes:
      - ./config/mysql/:/etc/mysql/conf.d:Z
  redis-test:
    image: redis:4-alpine
    command: redis-server
    tmpfs: /data
    networks:
      internal:
  test:
    image: uoregon-libraries/digital-exhibits-spotlight:201902261252
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app 
    expose:
      - 3000
    networks:
      internal:
      external:
    depends_on:
      - solr_test
      - db-test
      - redis-test
    environment:
      - RAILS_ENV=test
      - MAIL_SERVER=example.org
      - MAIL_SENDER=noreply@example.org
      - URL_HOST=localhost:3000
      - SOLR_URL=http://solr:8983/solr/test
      - OD_URL=https://oregondigital.org
      - REDIS_HOST=redis-test
      - REDIS_PORT='6379'
      - ACTIVE_JOB_QUEUE_ADAPTER=sidekiq
      - SIDEKIQ_ADMIN_SAFE_URLS='http://localhost:3000'
    command: >
      bash -c "./build/entrypoint.sh"

