version: '2'
services:
  solr: 
    image: solr:6.3.0
    ports:
      - "8983:8983"
    volumes:
      - data-solr-dev:/opt/solr/server/solr/mycores/
      - ./solr/config:/opt/solr/server/solr/configsets/data_driven_schema_configs
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    environment: 
      - VERBOSE=yes
  db:
    image: mariadb:5.5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ABRACADABRA
      - MYSQL_PASSWORD=ABRACADABRA
      - MYSQL_DATABASE=spotlightdev
      - MYSQL_USER=root
    volumes:
      - db:/var/lib/mysql
      - ./config/mysql/:/etc/mysql/conf.d:Z

  redis:
    image: redis:4-alpine
    command: redis-server
    volumes:
      - redis:/data

  web:
    image: uoregon-libraries/digital-exhibits-spotlight:202012031253
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app 
    ports:
      - "3000:3000"
    links:
      - solr
      - db
    environment:
      - MAIL_SERVER=example.org
      - MAIL_SENDER=noreply@example.org
      - URL_HOST=localhost:3000
      - SOLR_URL=http://solr:8983/solr/mycore
      - OD_URL=https://oregondigital.org
      - REDIS_HOST=redis
      - REDIS_PORT='6379'
      - ACTIVE_JOB_QUEUE_ADAPTER=sidekiq
      - SIDEKIQ_ADMIN_SAFE_URLS='http://localhost:3000'
    command: >
      bash -c "./build/entrypoint.sh"
    depends_on:
      - db
      - solr
      - redis

volumes:
  data-solr-dev: {}
  db: {}
  redis: {}
