name: Specs

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db-test:
        image: mariadb:5.5
        ports: ['3306:3306']
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: ABRACADABRA
          MYSQL_PASSWORD: ABRACADABRA
          MYSQL_DATABASE: spotlighttest
          MYSQL_USER: roto
      solr:
        image: solr:6.3.0
        ports: ['8983:8983']
    env:
      RAILS_ENV: test
      OD_URL: https://oregondigital.org
      URL_HOST: localhost:3000
      MAIL_SERVER: example.org
      MAIL_SENDER: noreply@example.org
      SOLR_URL: http://localhost:8983/solr/test
      MYSQL_HOST: 127.0.0.1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5
        bundler-cache: true
    
    - name: Rails setup
      run: bin/setup && bin/rails db:test:prepare
    - name: Prep solr
      run: |
        cd ./solr/config
        zip -1 -r solr_hyrax_config.zip ./*
        curl -H "Content-type:application/octet-stream" --data-binary @solr_hyrax_config.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=spotlight"
        curl -H 'Content-type: application/json' http://localhost:8985/api/collections/ -d '{create: {name: test, config: spotlight, numShards: 1}}'
    - name: Run tests
      run: bundle exec rspec spec

